/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainProfileRouteImport } from './routes/_main.profile'
import { Route as MainHomeRouteImport } from './routes/_main.home'
import { Route as MainCheckoutRouteImport } from './routes/_main.checkout'
import { Route as MainCartRouteImport } from './routes/_main.cart'
import { Route as MainProfileIndexRouteImport } from './routes/_main.profile.index'
import { Route as MainProfileOrdersRouteImport } from './routes/_main.profile.orders'
import { Route as MainProfileOrdersIndexRouteImport } from './routes/_main.profile.orders.index'
import { Route as MainProfileOrdersOrderIdRouteImport } from './routes/_main.profile.orders.$orderId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)
const MainCheckoutRoute = MainCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MainRoute,
} as any)
const MainCartRoute = MainCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileIndexRoute = MainProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainProfileRoute,
} as any)
const MainProfileOrdersRoute = MainProfileOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MainProfileRoute,
} as any)
const MainProfileOrdersIndexRoute = MainProfileOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainProfileOrdersRoute,
} as any)
const MainProfileOrdersOrderIdRoute =
  MainProfileOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => MainProfileOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cart': typeof MainCartRoute
  '/checkout': typeof MainCheckoutRoute
  '/home': typeof MainHomeRoute
  '/profile': typeof MainProfileRouteWithChildren
  '/profile/orders': typeof MainProfileOrdersRouteWithChildren
  '/profile/': typeof MainProfileIndexRoute
  '/profile/orders/$orderId': typeof MainProfileOrdersOrderIdRoute
  '/profile/orders/': typeof MainProfileOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cart': typeof MainCartRoute
  '/checkout': typeof MainCheckoutRoute
  '/home': typeof MainHomeRoute
  '/profile': typeof MainProfileIndexRoute
  '/profile/orders/$orderId': typeof MainProfileOrdersOrderIdRoute
  '/profile/orders': typeof MainProfileOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_main/cart': typeof MainCartRoute
  '/_main/checkout': typeof MainCheckoutRoute
  '/_main/home': typeof MainHomeRoute
  '/_main/profile': typeof MainProfileRouteWithChildren
  '/_main/profile/orders': typeof MainProfileOrdersRouteWithChildren
  '/_main/profile/': typeof MainProfileIndexRoute
  '/_main/profile/orders/$orderId': typeof MainProfileOrdersOrderIdRoute
  '/_main/profile/orders/': typeof MainProfileOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/profile'
    | '/profile/orders'
    | '/profile/'
    | '/profile/orders/$orderId'
    | '/profile/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/profile'
    | '/profile/orders/$orderId'
    | '/profile/orders'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/login'
    | '/register'
    | '/_main/cart'
    | '/_main/checkout'
    | '/_main/home'
    | '/_main/profile'
    | '/_main/profile/orders'
    | '/_main/profile/'
    | '/_main/profile/orders/$orderId'
    | '/_main/profile/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/home': {
      id: '/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/checkout': {
      id: '/_main/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof MainCheckoutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/cart': {
      id: '/_main/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof MainCartRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile/': {
      id: '/_main/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof MainProfileIndexRouteImport
      parentRoute: typeof MainProfileRoute
    }
    '/_main/profile/orders': {
      id: '/_main/profile/orders'
      path: '/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof MainProfileOrdersRouteImport
      parentRoute: typeof MainProfileRoute
    }
    '/_main/profile/orders/': {
      id: '/_main/profile/orders/'
      path: '/'
      fullPath: '/profile/orders/'
      preLoaderRoute: typeof MainProfileOrdersIndexRouteImport
      parentRoute: typeof MainProfileOrdersRoute
    }
    '/_main/profile/orders/$orderId': {
      id: '/_main/profile/orders/$orderId'
      path: '/$orderId'
      fullPath: '/profile/orders/$orderId'
      preLoaderRoute: typeof MainProfileOrdersOrderIdRouteImport
      parentRoute: typeof MainProfileOrdersRoute
    }
  }
}

interface MainProfileOrdersRouteChildren {
  MainProfileOrdersOrderIdRoute: typeof MainProfileOrdersOrderIdRoute
  MainProfileOrdersIndexRoute: typeof MainProfileOrdersIndexRoute
}

const MainProfileOrdersRouteChildren: MainProfileOrdersRouteChildren = {
  MainProfileOrdersOrderIdRoute: MainProfileOrdersOrderIdRoute,
  MainProfileOrdersIndexRoute: MainProfileOrdersIndexRoute,
}

const MainProfileOrdersRouteWithChildren =
  MainProfileOrdersRoute._addFileChildren(MainProfileOrdersRouteChildren)

interface MainProfileRouteChildren {
  MainProfileOrdersRoute: typeof MainProfileOrdersRouteWithChildren
  MainProfileIndexRoute: typeof MainProfileIndexRoute
}

const MainProfileRouteChildren: MainProfileRouteChildren = {
  MainProfileOrdersRoute: MainProfileOrdersRouteWithChildren,
  MainProfileIndexRoute: MainProfileIndexRoute,
}

const MainProfileRouteWithChildren = MainProfileRoute._addFileChildren(
  MainProfileRouteChildren,
)

interface MainRouteChildren {
  MainCartRoute: typeof MainCartRoute
  MainCheckoutRoute: typeof MainCheckoutRoute
  MainHomeRoute: typeof MainHomeRoute
  MainProfileRoute: typeof MainProfileRouteWithChildren
}

const MainRouteChildren: MainRouteChildren = {
  MainCartRoute: MainCartRoute,
  MainCheckoutRoute: MainCheckoutRoute,
  MainHomeRoute: MainHomeRoute,
  MainProfileRoute: MainProfileRouteWithChildren,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
